name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 🔹 1. Checkout
    - name: Checkout code
      uses: actions/checkout@v3

    # 🔹 2. Create frontend env
    - name: Create frontend .env
      run: |
        echo "VITE_API_URL=/api" > frontend/.env
        echo "VITE_STRIPE_KEY=pk_test_51TI7ArLQRiOYPdzktQHYsGukTiOKo8AGpfXxU6j1SSzFwDV3GVs7T2lTxauzEtibi3oqk9ojBS3N7OfC26NqJB3b00pO4pNnIi" >> frontend/.env

    # 🔹 3. Build frontend
    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    # 🔹 4. Upload FULL frontend folder (not dist)
    - name: Upload frontend folder
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: "frontend"
        target: "~/event-and-expense-tracker"

    # 🔹 5. Fix structure on VM (IMPORTANT STEP)
    - name: Fix frontend build structure
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd ~/event-and-expense-tracker

          echo "Cleaning old build..."
          rm -rf frontend_build/*
          
          echo "Moving new build..."
          cp -r frontend/dist/* frontend_build/

    # 🔹 6. Deploy backend
    - name: Deploy backend
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd ~/event-and-expense-tracker

          git pull origin main

          cd backend
          npm install

          pm2 restart backend || pm2 start server.js --name backend

          sudo systemctl reload nginx